apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "apigw.sonatypenxrm.com/v1alpha1",
          "kind": "SonatypeNXRM",
          "metadata": {
            "name": "example-sonatypenxrm"
          },
          "spec": {
            "config": {
              "data": null,
              "enabled": false,
              "mountPath": "/sonatype-nexus-conf"
            },
            "deployment": {
              "additionalContainers": null,
              "additionalVolumeMounts": null,
              "additionalVolumes": null,
              "annotations": {},
              "initContainers": null,
              "postStart": {
                "command": null
              }
            },
            "deploymentStrategy": {},
            "ingress": {
              "annotations": {},
              "enabled": false,
              "path": "/",
              "rules": null,
              "tls": {
                "enabled": true,
                "secretName": "nexus-tls"
              }
            },
            "nexus": {
              "dockerPort": 5003,
              "env": [
                {
                  "name": "install4jAddVmParams",
                  "value": "-Xms1200M -Xmx1200M -XX:MaxDirectMemorySize=2G -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
                },
                {
                  "name": "NEXUS_SECURITY_RANDOMPASSWORD",
                  "value": "false"
                }
              ],
              "hostAliases": [],
              "imageName": "registry.connect.redhat.com/sonatype/nexus-repository-manager",
              "imagePullPolicy": "IfNotPresent",
              "imagePullSecret": "",
              "imageTag": "3.20.1-01-ubi-3",
              "livenessProbe": {
                "failureThreshold": 6,
                "initialDelaySeconds": 30,
                "path": "/",
                "periodSeconds": 30
              },
              "nexusPort": 8081,
              "podAnnotations": {},
              "readinessProbe": {
                "failureThreshold": 6,
                "initialDelaySeconds": 30,
                "path": "/",
                "periodSeconds": 30
              },
              "resources": {},
              "securityContext": {
                "fsGroup": 2000
              },
              "service": {
                "type": "NodePort"
              }
            },
            "nexusProxyRoute": {
              "annotations": null,
              "enabled": false,
              "labels": null
            },
            "persistence": {
              "accessMode": "ReadWriteOnce",
              "enabled": true,
              "storageSize": "8Gi"
            },
            "replicaCount": 1,
            "route": {
              "annotations": null,
              "enabled": false,
              "labels": null,
              "name": "docker",
              "portName": "docker"
            },
            "secret": {
              "data": null,
              "enabled": false,
              "mountPath": "/etc/secret-volume",
              "readOnly": true
            },
            "service": {
              "annotations": {},
              "enabled": false,
              "labels": {},
              "ports": [
                {
                  "name": "nexus-service",
                  "port": 80,
                  "targetPort": 80
                }
              ]
            },
            "statefulset": {
              "enabled": false
            },
            "tolerations": []
          }
        }
      ]
    capabilities: Basic Install
  name: sonatypenxrm-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Placeholder description
  displayName: Sonatypenxrm Operator
  install:
    spec:
      deployments:
      - name: sonatypenxrm-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: sonatypenxrm-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: sonatypenxrm-operator
            spec:
              containers:
              - env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: sonatypenxrm-operator
                - name: RELATED_IMAGE_NEXUS
                  value: registry.connect.redhat.com/sonatype/nexus-repository-manager:3.20.1-01-ubi-3
                image: REPLACE_IMAGE
                imagePullPolicy: Always
                name: sonatypenxrm-operator
                resources: {}
              serviceAccountName: sonatypenxrm-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - ""
          resources:
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - sonatypenxrm-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        - apiGroups:
          - apigw.sonatypenxrm.com
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: sonatypenxrm-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  version: 0.0.0
